Update PublishNewApp.yml

diff --git a/.github/workflows/PublishNewApp.yml b/.github/workflows/PublishNewApp.yml
--- a/.github/workflows/PublishNewApp.yml
+++ b/.github/workflows/PublishNewApp.yml
@@ -54,9 +54,11 @@ jobs:
             echo "[INFO]: Setting up rclone config"
             echo "${{ secrets.RCLONE_CONFIG }}" | base64 -d > ~/.config/rclone/rclone.conf
             echo "[INFO]: Download db from gdrive"
-            rclone copy gdrive:/DB_Backups/Damianakos/sqlite.db API/sqlite.db
-
-
+            rclone copy gdrive:/DB_Backups/Damianakos/sqlite.db /root/app/API/sqlite.db
+            if [ ! -f API/sqlite.db ]; then
+              echo "[INFO]: Error: sqlite.db not found!"
+              exit 1
+            fi
 
 
 
